Desafio1/Web.Desafio1/Controllers/CidadeController.cs
using DataAccess.Desafio1.Generico;
using DomainModel.Desafio1.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Desafio1.Controllers
{
    public class CidadeController : Controller
    {
        #region Repositorio
        Repositorio repositorio = new Repositorio();
        #endregion

        public ActionResult List()
        {
            try
            {
                return View(repositorio.Cidade.ObterTodos());
            }
            catch (Exception ex)
            {
                Alerta(ex);
                return View(new List<Cidade>());
            }
        }

        public ActionResult Edit(int id = 0)
        {
            try
            {
                EnInclusao(id);
                return View(CarregarDropEstado(ObterCidade(id)));
            }
            catch (Exception ex)
            {
                Alerta(ex);
                return View(new Cidade());
            }
        }

        [HttpPost]
        public ActionResult Edit(Cidade entidade, int id = 0)
        {
            try
            {
                if (entidade.EstadoID.Equals(0))
                    return View(CarregarDropEstado(entidade));

                Cidade cidade = ObterCidade(id);
                cidade.Nome = entidade.Nome.ToUpper();
                cidade.Estado = repositorio.Estado.ObterPor(entidade.EstadoID);
                cidade.DataCadastro = id.Equals(0) ? DateTime.Now : cidade.DataCadastro;
                cidade.DataAtualizacao = DateTime.Now;
                cidade.Validar();
                repositorio.Cidade.Salvar(cidade);
                repositorio.SaveChanges();

                if (id.Equals(0))
                    return View(LimparTela());

                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Alerta(ex);
                return View(CarregarDropEstado(new Cidade()));
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                Cidade cidade = ObterCidade(id);
                string nomeCidade = cidade.Nome;
                repositorio.Cidade.Excluir(cidade);
                repositorio.SaveChanges();
                TempData["Alerta"] = $"Cidade: <b>{nomeCidade}</b> foi excluido do sistema!";
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Alerta(ex);
                return RedirectToAction("List");
            }
        }

        public ActionResult ListaCidadesPorIdEstado(int estadoID)
        {
            return Json(repositorio.Cidade.ObterCidadePorEstadoID(estadoID), JsonRequestBehavior.AllowGet);
        }

        #region Metodos Privados
        private Cidade CarregarDropEstado(Cidade cidade)
        {
            ViewBag.EstadoID = new SelectList
                (
                    repositorio.Estado.ObterTodos(),
                    "ID",
                    "Nome",
                    cidade.EstadoID
                );
            return cidade;
        }

        private Cidade ObterCidade(int id)
        {
            return id.Equals(0) ? new Cidade() : repositorio.Cidade.ObterPor(id);
        }

        private Cidade LimparTela()
        {
            TempData["Mensagem"] = "Sucesso";
            ModelState.Clear();
            EnInclusao(0);
            return CarregarDropEstado(new Cidade());
        }

        private void EnInclusao(int id)
        {
            TempData["EnInclusao"] = id.Equals(0) ? "Cadastro Cidade" : "Edição Cidade";
        }

        private void Alerta(Exception ex)
        {
            TempData["Alerta"] = ex.Message.Replace(Environment.NewLine, "</br>");
        }
        #endregion

    }
}

Desafio1/Web.Desafio1/Views/Cidade/Edit.cshtml
@model DomainModel.Desafio1.Classes.Cidade

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="layoutSidenav_content">
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">
                                @Html.Raw(TempData["EnInclusao"])
                            </h3>
                        </div>
                        <div class="card-body">

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()
                                <form>
                                    <div class="form-row">
                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "small mb-1" })
                                            <div class="form-group">
                                                @Html.EditorFor(model => model.Nome, "Nome", new { htmlAttributes = new { @class = "form-control py-6" } })
                                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-7">
                                            @Html.LabelFor(model => model.EstadoID, "Estado", htmlAttributes: new { @class = "small mb-1" })
                                            <div class="form-group">
                                                @Html.DropDownList("EstadoID", "")
                                                @Html.ValidationMessageFor(model => model.EstadoID, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <div class="small"></div>
                                        <input type="submit" value="Salvar" class="btn btn-primary" />
                                    </div>
                                </form>
                            }

                            <!-- Botão oculto que abre o modal de SUCESSO-->
                            <button id="btnModalSucesso" type="button" style="display: none;" data-toggle="modal" data-target="#modalSucesso"></button>

                            @if (TempData["Mensagem"] == "Sucesso")
                            {<!-- Modal -->
                                <div id="modalSucesso" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <div class="modal-content">

                                            <!-- Cabeçalho do modal -->
                                            <div class="modal-header">

                                                <h4 class="modal-title">
                                                    SUCESSO
                                                    <i class="fas fa-check"></i>
                                                </h4>
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            <!-- Corpo do modal -->
                                            <div class="modal-body">
                                                <p>Foi incluído uma nova <b>cidade</b> no sistema</p>
                                            </div>

                                            <!-- Rodapé do modal-->
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }

                            <!-- Botão oculto que abre o modal de Alerta -->
                            <button id="btnModalErro" type="button" style="display: none;" data-toggle="modal" data-target="#modalErro"></button>

                            @if (TempData["Alerta"] != null)
                            {<!-- Modal -->
                                <div id="modalErro" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <div class="modal-content">

                                            <!-- Cabeçalho do modal -->
                                            <div class="modal-header">
                                                <h4 class="modal-title">
                                                    ATENÇÃO
                                                    <i class="fas fa-exclamation-triangle"></i>
                                                </h4>
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            <!-- Corpo do modal -->
                                            <div class="modal-body">
                                                <p>
                                                    @Html.Raw(@TempData["Alerta"])
                                                </p>
                                            </div>
                                            <!-- Rodapé do modal-->
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        @*<script src="~/Scripts/jquery-3.4.1.min.js"></script>*@
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
        @section Scripts {
            <script>
                $(document).ready(function () {
                    $("#btnModalSucesso").click();
                    $("#btnModalErro").click();
                    $("#EstadoID").addClass("form-control");
                });</script>
        }
    </main>
</div>


@*<h2>Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Cidade</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-7">
                @Html.LabelFor(model => Model.EstadoID, "Estado", htmlAttributes: new { @class = "small mb-1" })
                <div class="form-group">
                    @Html.DropDownList("DropEstado", "Selecione Estado")
                    @Html.ValidationMessageFor(model => model.EstadoID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

Desafio1/Web.Desafio1/Views/Cidade/List.cshtml
@model IEnumerable<DomainModel.Desafio1.Classes.Cidade>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <div class="mt-4"></div>

            <div class="card mb-4">
                <a href="@Url.Action("Edit","Cidade")">
                    <div class="card-header">
                        <i class="fas fa-plus mr-1"></i>
                        Incluir Cidade
                    </div>
                </a>

                <div class="card-body">
                    <div class="table-responsive">

                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Editar</th>
                                    <th>Cidade</th>
                                    <th>Estado</th>
                                    <th>Excluir</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <a class="nav-link" href="@Url.Action("Edit", "Cidade", new { id = item.ID })">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                        </td>
                                        <td>@item.Nome</td>
                                        <td>@item.Estado.Nome</td>
                                        <td>
                                            <a class="nav-link" href="@Url.Action("Delete", "Cidade", new { id = item.ID })">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- Botão oculto que abre o modal de Alerta -->
                    <button id="btnModalErro" type="button" style="display: none;" data-toggle="modal" data-target="#modalErro"></button>

                    @if (TempData["Alerta"] != null)
                    {<!-- Modal -->
                        <div id="modalErro" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">

                                    <!-- Cabeçalho do modal -->
                                    <div class="modal-header">
                                        <h4 class="modal-title">
                                            ATENÇÃO
                                            <i class="fas fa-exclamation-triangle"></i>
                                        </h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <!-- Corpo do modal -->
                                    <div class="modal-body">
                                        <p>
                                            @Html.Raw(@TempData["Alerta"])
                                        </p>
                                    </div>
                                    <!-- Rodapé do modal-->
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        @*<script src="~/Scripts/jquery-3.4.1.min.js"></script>*@
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
        @section Scripts {
            <script>
                $(document).ready(function () {
                    $("#btnModalSucesso").click()
                    $("#btnModalErro").click()
                });</script>
        }
    </main>
</div>

@*<h2>List</h2>

    <p>
        @Html.ActionLink("Create New", "Edit")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
    }

    </table>*@