Desafio1/Web.Desafio1/Controllers/EstadoController.cs
using DataAccess.Desafio1.Generico;
using DomainModel.Desafio1.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Desafio1.Controllers
{
    public class EstadoController : Controller
    {
        #region Repositorio
        Repositorio repositorio = new Repositorio();
        #endregion

        public ActionResult List()
        {
            try
            {
                return View(repositorio.Estado.ObterTodos());
            }
            catch (Exception ex)
            {
                Alerta(ex);
                return View(new List<Estado>());
            }
        }

        public ActionResult Edit(int id = 0)
        {
            Estado estado = new Estado();
            try
            {
                EnInclucao(id);
                return View(ObterEstado(id));
            }
            catch (Exception ex)
            {
                Alerta(ex);
                return View(estado);
            }
        }

        [HttpPost]
        public ActionResult Edit(Estado entidade, int id = 0)
        {
            try
            {
                Estado estado = ObterEstado(id);
                estado.Nome = entidade.Nome == null ? string.Empty : entidade.Nome.ToUpper();
                estado.UF = entidade.UF == null ? string.Empty : entidade.UF.ToUpper();
                estado.DataCadastro = id.Equals(0) ? DateTime.Now : estado.DataCadastro;
                estado.DataAtualizacao = DateTime.Now;
                estado.Validar();
                repositorio.Estado.Salvar(estado);
                repositorio.SaveChanges();

                if (id.Equals(0))
                    return View(LimparTela());

                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Alerta(ex);
                return View(new Estado());
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                Estado estado = ObterEstado(id);
                string nomeEstado = estado.Nome;
                repositorio.Estado.Excluir(estado);
                repositorio.SaveChanges();
                TempData["Alerta"] = $"Estado: <b>{nomeEstado}</b> foi excluido do sistma";
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Alerta(ex);
                return RedirectToAction("List");
            }
        }

        public ActionResult ObterEstadoPorUF(string uf)
        {
            return Json(repositorio.Estado.ObterEstadoPorUF(uf), JsonRequestBehavior.AllowGet);
        }

        #region Métodos Privados
        private void Alerta(Exception ex)
        {
            TempData["Alerta"] = ex.Message.Replace(Environment.NewLine, "</br>");
        }

        private void EnInclucao(int id)
        {
            TempData["EnInclusao"] = id.Equals(0) ? "Cadastro Estado" : "Edição Estado";
        }

        private Estado ObterEstado(int id)
        {
            return id.Equals(0) ? new Estado() : repositorio.Estado.ObterPor(id);
        }

        private Estado LimparTela()
        {
            TempData["Mensagem"] = "Sucesso";
            ModelState.Clear();
            EnInclucao(0);
            return new Estado();
        }
        #endregion
    }
}

Desafio1/Web.Desafio1/Views/Estado/Edit.cshtml
@model DomainModel.Desafio1.Classes.Estado

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="layoutSidenav_content">
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">
                                @Html.Raw(TempData["EnInclusao"])
                            </h3>
                        </div>
                        <div class="card-body">

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()
                                <form>
                                    <div class="form-row">
                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "small mb-1" })
                                            <div class="form-group">
                                                @Html.EditorFor(model => model.Nome, "Curso", new { htmlAttributes = new { @class = "form-control py-6" } })
                                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-3">
                                            @Html.LabelFor(model => model.UF, htmlAttributes: new { @class = "small mb-1" })
                                            <div class="form-group">
                                                @Html.EditorFor(model => model.UF, "Curso", new { htmlAttributes = new { @class = "form-control py-6" } })
                                                @Html.ValidationMessageFor(model => model.UF, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <div class="small"></div>
                                        <input type="submit" value="Salvar" class="btn btn-primary" />
                                    </div>
                                </form>
                            }

                            <!-- Botão oculto que abre o modal de SUCESSO-->
                            <button id="btnModalSucesso" type="button" style="display: none;" data-toggle="modal" data-target="#modalSucesso"></button>

                            @if (TempData["Mensagem"] == "Sucesso")
                            {<!-- Modal -->
                                <div id="modalSucesso" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <div class="modal-content">

                                            <!-- Cabeçalho do modal -->
                                            <div class="modal-header">

                                                <h4 class="modal-title">
                                                    SUCESSO
                                                    <i class="fas fa-check"></i>
                                                </h4>
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            <!-- Corpo do modal -->
                                            <div class="modal-body">
                                                <p>Foi incluído um novo estado no sistema </p>
                                            </div>

                                            <!-- Rodapé do modal-->
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }

                            <!-- Botão oculto que abre o modal de Alerta -->
                            <button id="btnModalErro" type="button" style="display: none;" data-toggle="modal" data-target="#modalErro"></button>

                            @if (TempData["Alerta"] != null)
                            {<!-- Modal -->
                                <div id="modalErro" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <div class="modal-content">

                                            <!-- Cabeçalho do modal -->
                                            <div class="modal-header">
                                                <h4 class="modal-title">
                                                    ATENÇÃO
                                                    <i class="fas fa-exclamation-triangle"></i>
                                                </h4>
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            <!-- Corpo do modal -->
                                            <div class="modal-body">
                                                <p>
                                                    @Html.Raw(@TempData["Alerta"])
                                                </p>
                                            </div>
                                            <!-- Rodapé do modal-->
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        @*<script src="~/Scripts/jquery-3.4.1.min.js"></script>*@
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
        @section Scripts {
            <script>
                $(document).ready(function () {
                    $("#btnModalSucesso").click()
                    $("#btnModalErro").click()
                });</script>
        }
    </main>
</div>

Desafio1/Web.Desafio1/Views/Estado/List.cshtml
@model IEnumerable<DomainModel.Desafio1.Classes.Estado>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <div class="mt-4"></div>

            <div class="card mb-4">
                <a href="@Url.Action("Edit","Estado")">
                    <div class="card-header">
                        <i class="fas fa-plus mr-1"></i>
                        Incluir Estado
                    </div>
                </a>

                <div class="card-body">
                    <div class="table-responsive">

                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Editar</th>
                                    <th>Estado</th>
                                    <th>UF</th>
                                    <th>Excluir</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <a class="nav-link" href="@Url.Action("Edit", "Estado", new { id = item.ID })">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                        </td>
                                        <td>@item.Nome</td>
                                        <td>@item.UF</td>
                                        <td>
                                            <a class="nav-link" href="@Url.Action("Delete", "Estado", new { id = item.ID })">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- Botão oculto que abre o modal de Alerta -->
                    <button id="btnModalErro" type="button" style="display: none;" data-toggle="modal" data-target="#modalErro"></button>

                    @if (TempData["Alerta"] != null)
                    {<!-- Modal -->
                        <div id="modalErro" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">

                                    <!-- Cabeçalho do modal -->
                                    <div class="modal-header">
                                        <h4 class="modal-title">
                                            ATENÇÃO
                                            <i class="fas fa-exclamation-triangle"></i>
                                        </h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <!-- Corpo do modal -->
                                    <div class="modal-body">
                                        <p>
                                            @Html.Raw(@TempData["Alerta"])
                                        </p>
                                    </div>
                                    <!-- Rodapé do modal-->
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        @*<script src="~/Scripts/jquery-3.4.1.min.js"></script>*@
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
        @section Scripts {
            <script>
                $(document).ready(function () {
                    $("#btnModalSucesso").click()
                    $("#btnModalErro").click()
                });</script>
        }
    </main>
</div>